- name: Configure docker with guest
  hosts: default
  become: True
  tasks:
    - package:
      name: "{{item}}"
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: install pip
      apt: name=python-pip update_cache=yes state=present

    - name: install docker-py
      pip: name=docker-py

    # Add apt keys
    - name: add key for ppa python repository
      apt_key: keyserver=keyserver.ubuntu.com id=DB82666C state=present
      become: yes
      become_user: root
      become_method: sudo

    # Add extra repositories
    - name: Add ppa python repository
      apt_repository: repo='deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main' state=present update_cache=yes
      become: yes
      become_user: root
      become_method: sudo

    # Update python version
    - name: ensure python2.7 latest is installed
      apt:
        pkg: python2.7
        state: latest
        install_recommends: no
      become: yes
      become_user: root
      become_method: sudo

    - name: Add Docker GPG Key
      apt_key:  
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 
        state: present 
      register: add_repository_key 
      ignore_errors: true

    - name: Add Docker apt key (alternative for older systems without SNI).
      shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      args:
        warn: no
      when: add_repository_key is failed

    - name: Add Docker APT Repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable"

    - name: install docker
      apt: name=docker-ce update_cache=yes

    - name:  add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes    

    - name: start docker
      service: name=docker enabled=yes state=started

    - name: create alpine docker container
      docker_image:
        docker_api_version: 1.37
        name: adc
        path: /vagrant/container
        state: present

    - name: create nginx container
      docker_container:
        name: nginx_alpine
        image: adc
        ports: 8888:8888
        state: started
